# 异常处理 - Try..Catch



## 异常

编码错误、由于错误输入引起的错误，或者其他无法预见的情况。

当发生错误时，C# 通常会停止并生成一个错误消息。这个过程的技术术语是：C# 将抛出一个异常（产生一个错误）。



## try and catch

- `try` 语句允许您定义一个在执行过程中被测试错误的代码块。

- `catch` 语句允许您定义一个在 `try` 块中发生错误时执行的代码块。

- `try` 和 `catch` 关键字是成对出现的：

### 语法

```c#
try 
{
  //  Block of code to try
}
catch (Exception e)
{
  //  Block of code to handle errors
}
```



考虑以下示例，我们创建一个包含三个整数的数组：

这将生成一个错误，因为`myNumbers[10]`不存在。

```c#
int[] myNumbers = {1, 2, 3};
Console.WriteLine(myNumbers[10]); // error!
```

错误消息将类似于：

```bash
System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'
```




如果发生错误，我们可以使用 `try...catch` 来捕获错误并执行一些代码来处理它。

在以下示例中，我们使用 `catch` 块中的变量（`e`），以及内置的 `Message` 属性，它输出描述异常的消息：

### 示例：

```c#
try
{
  int[] myNumbers = {1, 2, 3};
  Console.WriteLine(myNumbers[10]);
}
catch (Exception e)
{
  Console.WriteLine(e.Message);
}
```



你也可以输出自己的错误消息：

### 示例：

```c#
try
{
  int[] myNumbers = {1, 2, 3};
  Console.WriteLine(myNumbers[10]);
}
catch (Exception e)
{
  Console.WriteLine("Something went wrong.");
}

// Something went wrong.
```





## Finally

`finally` 语句允许您在 `try...catch` 之后执行代码，无论结果如何：

### 示例：

```c#
try
{
  int[] myNumbers = {1, 2, 3};
  Console.WriteLine(myNumbers[10]);
}
catch (Exception e)
{
  Console.WriteLine("Something went wrong.");
}
finally
{
  Console.WriteLine("The 'try catch' is finished.");
}

// Something went wrong.
// The 'try catch' is finished.
```





## throw  关键字

`throw` 语句允许您创建自定义错误。

`throw` 语句与异常类一起使用。在 C# 中有许多异常类可用，例如：`ArithmeticException`、`FileNotFoundException`、`IndexOutOfRangeException`、`TimeOutException` 等：

### 示例：

```c#
static void checkAge(int age)
{
  if (age < 18)
  {
    throw new ArithmeticException("Access denied - You must be at least 18 years old.");
  }
  else
  {
    Console.WriteLine("Access granted - You are old enough!");
  }
}

static void Main(string[] args)
{
  checkAge(15);
}

// System.ArithmeticException: 'Access denied - You must be at least 18 years old.'
```

